services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - ./server:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./view
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
