services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY} # Variável de ambiente da API do YouTube
    env_file:
      - .env
    volumes:
      - ./server:/app
    depends_on:
      - redis
    command: >
      sh -c 'if [ "$$RUN_SEED" = "true" ]; then
                echo "Rodando seed...";
                sqlite3 /app/instance/videos.db ".read /app/infrastructure/scripts/seed_videos.sql";
             fi &&
             echo "Iniciando o servidor Flask..." &&
             flask run --host=0.0.0.0'

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app-frontend:/app
    depends_on:
      - backend
