CREATE TABLE IF NOT EXISTS videos (
    id TEXT PRIMARY KEY,
    url TEXT NOT NULL,
    title TEXT NOT NULL,
    thumbnail TEXT,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
 
INSERT INTO videos (id, url, title, thumbnail, description, created_at) VALUES
('kXYiU_JCYtU', 'https://www.youtube.com/watch?v=kXYiU_JCYtU&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH', 'Numb (Official Music Video) [4K UPGRADE] – Linkin Park', 'https://i.ytimg.com/vi/kXYiU_JCYtU/hqdefault.jpg', 'Numb (Official Music Video) [4K UPGRADE] – Linkin Park\n----------\nFrom Zero | The New Album | Available November 15th\nPre-Order Now: https://lprk.co/fromzero\n\nOfficial Linkin Park Merch: http://lprk.co/store\nText/Call: https://lprk.co/text\nNewsletter Sign Up: https://lprk.co/newsletter\nYouTube Subscribe: http://lprk.co/youtube\nFacebook: http://lprk.co/facebook\nInstagram: http://lprk.co/instagram\nTikTok: http://lprk.co/tiktok\nTwitter: http://lprk.co/twitter\nDiscord: https://discord.gg/linkinpark\n\n#LinkinPark #Meteora #Lost #Meteora20', '2024-10-08 22:56:32.245100'),
('8SbUC-UaAxE', 'https://www.youtube.com/watch?v=8SbUC-UaAxE&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=2', 'Guns N'' Roses - November Rain', 'https://i.ytimg.com/vi/8SbUC-UaAxE/hqdefault.jpg', 'Official Music Video for "November Rain" performed by Guns N'' Roses from their third studio album, ''Use Your Illusion I.'' Featured in Thor: Love and Thunder.\n\nSubscribe to Guns N'' Roses YouTube channel and never miss an update: https://GNR.lnk.to/YouTube\n\n#GunsNRoses #GnR #NovemberRain', '2024-10-08 22:56:36.852592'),
('hTWKbfoikeg', 'https://www.youtube.com/watch?v=hTWKbfoikeg&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=3', 'Nirvana - Smells Like Teen Spirit (Official Music Video)', 'https://i.ytimg.com/vi/hTWKbfoikeg/hqdefault.jpg', 'Official Music Video for Smells Like Teen Spirit performed by Nirvana.\n\n#Nirvana #Breed #Nevermind', '2024-10-08 22:56:40.406799'),
('eVTXPUF4Oz4', 'https://www.youtube.com/watch?v=eVTXPUF4Oz4&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=4', 'In The End [Official HD Music Video] - Linkin Park', 'https://i.ytimg.com/vi/eVTXPUF4Oz4/hqdefault.jpg', 'In The End [Official HD Music Video] - Linkin Park\n\n#LinkinPark #InTheEnd', '2024-10-08 22:56:45.493395'),
('6NXnxTNIWkc', 'https://www.youtube.com/watch?v=6NXnxTNIWkc&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=5', '4 Non Blondes - What''s Up (Official Music Video)', 'https://i.ytimg.com/vi/6NXnxTNIWkc/hqdefault.jpg', 'CELEBRATING ONE BILLION VIEWS!! REMASTERED IN HD!\n\n#4NonBlones #WhatsUp', '2024-10-08 22:56:48.992470'),
('fJ9rUzIMcZQ', 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=6', 'Queen – Bohemian Rhapsody (Official Video Remastered)', 'https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg', 'REMASTERED IN HD TO CELEBRATE ONE BILLION VIEWS!\n\n#QueenTheGreatest #BohemianRhapsody', '2024-10-08 22:56:53.231765'),
('1w7OgIMMRc4', 'https://www.youtube.com/watch?v=1w7OgIMMRc4&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=7', 'Guns N'' Roses - Sweet Child O'' Mine (Official Music Video)', 'https://i.ytimg.com/vi/1w7OgIMMRc4/hqdefault.jpg', 'Official Music Video for "Sweet Child O'' Mine" by Guns N'' Roses as featured in Thor: Love and Thunder.\n\n#GunsNRoses #GnR', '2024-10-08 22:56:56.862276'),
('bpOSxM0rNPM', 'https://www.youtube.com/watch?v=bpOSxM0rNPM&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=8', 'Arctic Monkeys - Do I Wanna Know? (Official Video)', 'https://i.ytimg.com/vi/bpOSxM0rNPM/hqdefault.jpg', 'Arctic Monkeys - ''Do I Wanna Know?'' from ''AM'', released 2013 on Domino Recording Co.\n\n#ArcticMonkeys #AM', '2024-10-08 22:57:01.048198'),
('Soa3gO7tL-c', 'https://www.youtube.com/watch?v=Soa3gO7tL-c&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=9', 'Green Day - Boulevard Of Broken Dreams [Official Music Video]', 'https://i.ytimg.com/vi/Soa3gO7tL-c/hqdefault.jpg', 'Watch the official music video for Boulevard Of Broken Dreams by Green Day from the album American Idiot.\n\n#GreenDay #BoulevardOfBrokenDreams', '2024-10-08 22:57:04.739260'),
('SJJI4TchE08', 'https://www.youtube.com/watch?v=SJJI4TchE08&list=PL_Q15fKxrBb7wo5SRxHbhk6ZL6zMYh5tH&index=10', 'Beartooth - "ATTN." (Official Music Video) | The Surface: Deluxe Edition', 'https://i.ytimg.com/vi/SJJI4TchE08/hqdefault.jpg', 'Beartooth - "ATTN." from ''The Surface: Deluxe Edition''.\n\n#Beartooth #ATTN', '2024-10-08 22:57:08.946762'),
('DWaB4PXCwFU','https://www.youtube.com/watch?v=DWaB4PXCwFU','Breaking Benjamin - The Diary of Jane','https://i.ytimg.com/vi/DWaB4PXCwFU/hqdefault.jpg','Breaking Benjamin latest album DARK BEFORE DAWN featuring the singles “Failure,” “Angels Fall,” and “Ashes of Eden” is available now!\nApple: http://smarturl.it/bba1\nAmazon: http://smarturl.it/bbama1\nStreaming: http://smarturl.it/bbsta1\n\nFollow Breaking Benjamin\nhttp://facebook.com/BreakingBenjamin\nhttp://twitter.com/breakingbenj\nhttp://instagram.com/breakingbenjamin\n\nMusic video by Breaking Benjamin performing The Diary of Jane.','2024-10-09T20:42:32.296952+00:00'),
('Vrr3lRLjZ1Y','https://www.youtube.com/watch?v=Vrr3lRLjZ1Y','Crossfade - Cold','https://i.ytimg.com/vi/Vrr3lRLjZ1Y/hqdefault.jpg','Crossfade''s official music video for ''Cold''. Click to listen to Crossfade on Spotify: http://smarturl.it/CrossfadeSpotify?I...\n\nAs featured on Crossfade. Click to buy the track or album via\niTunes: http://smarturl.it/CrossfadeAlbum?IQi...\nGoogle Play: http://smarturl.it/CrossfadeColdGplay...\nAmazon: http://smarturl.it/CrossfadeAmazon?IQ...\n\nMore from Crossfade\nDrown You Out: https://youtu.be/la0nM6uRRMk\nInvincible: https://youtu.be/9mkAkHkBjnY\nColors: https://youtu.be/PYw0mg8RPKA\n\nMore great Alternative videos here: http://smarturl.it/Alternative00?IQid...\n\nFollow Crossfade\nWebsite: http://www.crossfadeband.com/\nFacebook: https://www.facebook.com/crossfadeband\nTwitter: https://twitter.com/crossfademusic\n\nSubscribe to Crossfade on YouTube: http://smarturl.it/CrossfadeSub?IQid=...\n\n---------\n\nLyrics:\n\nLooking back at me I see\nThat I never really got it right\nI never stopped to think of you\nI''m always wrapped up in\nThings I cannot win\nYou are the antidote that gets me by\nSomething strong\nLike a drug that gets me high\n\nWhat I really meant to say\nIs I''m sorry for the way I am\nI never meant to be so cold \n\nTo you I''m sorry about all the lies\nMaybe in a different light\nYou could see me stand on my own again\nCause now i can see\nYou were the antidote that got me by\nSomething strong like a drug that got me high','2024-10-09T20:44:53.663255+00:00');


-- sqlite3 instance/videos.db < infrastructure/scripts/seed_videos.sql